# -*- coding: utf-8 -*-
"""
Created on Wed Apr 15 10:06:17 2020

@author: thinkpad
"""

seq1 = '''MLSRAVCGTSRQLAPVLAYLGSRQKHSLPDLPYDYGALEPHINAQIMQLHHSKHHAAYVNNLNVTEEKYQEALAKGDVTAQIALQPALKFNGGGHINHSIFWTNLSPNGGGEPKGELLEAIKRDFGSFDKFKEKLTAASVGVQGSGWGWLGFNKERGHLQIAACPNQDPLQGTTGLIPLLGIDVWEHAYYLQYKNVRPDYLKAIWNVINWENVTERYMACKK'''
seq2 = '''MLCRAACSTGRRLGPVAGAAGSRHKHSLPDLPYDYGALEPHINAQIMQLHHSKHHAAYVNNLNATEEKYHEALAKGDVTTQVALQPALKFNGGGHINHTIFWTNLSPKGGGEPKGELLEAIKRDFGSFEKFKEKLTAVSVGVQGSGWGWLGFNKEQGRLQIAACSNQDPLQGTTGLIPLLGIDVWEHAYYLQYKNVRPDYLKAIWNVINWENVTERYTACKK'''
seq3 = '''WNGFSEWWTHEVDYNQKLTIENNQRPKIHEHEQWGLRQSPPPPKLCCPTCQMCERMRHQNRFAPLMEVGCRCMCWFHDWWVISVGTWLHTVIMYMMWPKRFHHNECPKACFRTTYTRKNHHALYWMLFEMCCYDQDVVWSKTHIFTTVRDIEVYVEQVFFIWGPLCHVAIACYEPVKTIRRRIPMYLCRHCIRGDNSYLLACCSIIYYFYHHMSYYGVLDIL'''

edit_distance =	0 
for	i in range(len(seq1)): 
    if seq1[i] != seq2[i]:		
        edit_distance += 1 
print (100-edit_distance/len(seq1)*100,'%')

edit_distance =	0 
for	i in range(len(seq1)): 
    if seq3[i] != seq1[i]:		
        edit_distance += 1 
print (100-edit_distance/len(seq1)*100,'%')

edit_distance =	0 
for	i in range(len(seq1)): 
    if seq2[i] != seq3[i]:		
        edit_distance += 1 
print (100-edit_distance/len(seq1)*100,'%')